### PR TITLE
Multiple Lists

### PR DESCRIPTION
**Pull request by CameronMunroe**

### CODE REVIEW

**Comment by CameronMunroe** [comment]
I attempted to build out a multiple lists idea. 

Definitely needs a read through, and a second pair of eyes.

**Comment by splitice** [comment]
A matrix and single CI script would be better. Thats how it's going to be built.

**Comment by CameronMunroe** [comment]
> A matrix and single CI script would be better. Thats how it's going to be built.

I do think maintainability will go down because of a single CI script. If one part fails the whole thing comes crashing down.

**Comment by splitice** [comment]
I have to maintain this repository so unfortunately you have to live with my decision.

More DRY code = Less effort to maintain in my books. And a CI matrix is the common way to do this. 

This does not impact script success / failure anyway. Thats not how test matrixes work.

Anyway I'll do this seperation eventually. Its just not a huge priority compared to everything else on my plate currently.

If you wish to contribute, do so under a matrix based design. Or stick to contributing a split ASN list or something and leave the CI to me to get to at some point.

**Pull request closed without merging**
