### PR TITLE
Fixed ASN list formatting

### PR DESCRIPTION
**Pull request by mhajder**

### CODE REVIEW

**Comment by splitice** [comment]
Would you mind expanding?

**Comment by mhajder** [comment]
I meant only the file formatting so that there is a space after #. It would also be necessary to check the organization of a given ASN from scratch, later I wants to change it more to something like "# <Name>, <country code>" to make it uniform.

**Comment by splitice** [comment]
I do not disagree. Seems reasonable, accepted.

**Comment by mhajder** [comment]
I still have a little question, could you please add the "hacktoberfest" tag to the repository? It's only temporary.

**Pull request merged**
